#!/usr/bin/env python3
"""
Build and validate Atari 2600 assembly code using dasm and headless Stella.

Usage:
    python3 build_and_run.py <source.asm> [output.a26]

Assembles the source with dasm, then runs the resulting ROM in headless Stella
with a debug script to validate scanline count and capture ROM state.

Requirements (included in devcontainer):
    - dasm assembler
    - Stella emulator with logexec patch
    - xvfb for headless display
"""

import sys
import subprocess
import re
from pathlib import Path

STELLA_PATH = "/usr/bin/stella"

DEFAULT_SCRIPT = """\
frame #60
print _scanEnd
exitRom
"""

EXPECTED_SCANLINES_NTSC = 262
EXPECTED_SCANLINES_PAL = 312


def assemble(source_path, output_file):
    """Assemble source with dasm. Returns True on success."""
    print(f"Assembling {source_path.name} with dasm...")

    dasm_cmd = [
        "dasm",
        source_path.name,
        f"-o{output_file}",
        "-f3",
        "-v0",
        f"-l{output_file.with_suffix('.lst')}",
        f"-s{output_file.with_suffix('.sym')}",
    ]

    try:
        result = subprocess.run(
            dasm_cmd, capture_output=True, text=True, cwd=source_path.parent
        )
    except FileNotFoundError:
        print("Assembly FAILED: dasm assembler not found")
        return False

    if result.returncode != 0:
        print("Assembly FAILED:")
        if result.stderr:
            print(result.stderr)
        if result.stdout:
            print(result.stdout)
        return False

    if not output_file.exists() or output_file.stat().st_size == 0:
        print("Assembly FAILED: output file not created or empty")
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr)
        return False

    rom_size = output_file.stat().st_size
    print(f"Assembly OK: {output_file} ({rom_size} bytes)")

    if result.stdout.strip():
        print(result.stdout.strip())

    return True


def run_headless_stella(rom_path, script_path):
    """Run ROM in headless Stella with debug script. Returns the output text or None."""
    userdir = rom_path.parent.resolve()

    stella_cmd = [
        "xvfb-run", "-a",
        STELLA_PATH,
        "-debug",
        "-dbg.logexec", "1",
        "-dbg.script", str(script_path.resolve()),
        "-userdir", str(userdir),
        str(rom_path.resolve()),
    ]

    print("Running headless Stella...")

    try:
        subprocess.run(stella_cmd, capture_output=True, text=True, timeout=60)
    except subprocess.TimeoutExpired:
        print("WARNING: Stella timed out after 60 seconds")
    except FileNotFoundError:
        print("ERROR: xvfb-run or stella not found")
        return None

    output_file = rom_path.parent / (script_path.name + ".output.txt")
    if output_file.exists():
        return output_file.read_text()

    print("WARNING: No script output file generated by Stella")
    return None


def parse_and_report(output_text, rom_path):
    """Parse Stella debug output and report validation results.

    Returns True if validation passes.
    """
    scanline_count = None

    for line in output_text.splitlines():
        stripped = line.strip()

        # Skip prompt lines and errors from comments
        if stripped.startswith("> "):
            continue
        if "No such command" in stripped:
            continue
        if not stripped:
            continue

        # Parse _scanEnd value: look for #NNN decimal output
        if "#" in line and ("_scanEnd" not in line):
            match = re.search(r"#(\d+)\s*$", line)
            if match:
                scanline_count = int(match.group(1))

    # Report results
    print("\n--- Validation Results ---")
    passed = True

    if scanline_count is not None:
        if scanline_count == EXPECTED_SCANLINES_NTSC:
            print(f"Scanlines: {scanline_count} (NTSC OK)")
        elif scanline_count == EXPECTED_SCANLINES_PAL:
            print(f"Scanlines: {scanline_count} (PAL OK)")
        else:
            print(f"Scanlines: {scanline_count} (EXPECTED {EXPECTED_SCANLINES_NTSC} for NTSC or {EXPECTED_SCANLINES_PAL} for PAL)")
            passed = False
    else:
        print("Scanlines: could not determine (no _scanEnd in output)")

    # Check for snapshots
    snapshots = list(rom_path.parent.glob(f"*{rom_path.stem}*.png"))
    if snapshots:
        print(f"\nSnapshot saved: {snapshots[-1].name}")

    return passed


def build_and_run(source_file, output_file=None):
    """Build assembly file with dasm and validate in headless Stella."""
    source_path = Path(source_file).resolve()

    if not source_path.exists():
        print(f"Error: Source file '{source_file}' not found")
        return False

    # Determine output filename
    if output_file is None:
        build_dir = source_path.parent.parent / "build"
        if build_dir.exists():
            output_file = build_dir / source_path.with_suffix(".a26").name
        else:
            output_file = source_path.with_suffix(".a26")
    else:
        output_file = Path(output_file).resolve()

    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Step 1: Assemble
    if not assemble(source_path, output_file):
        return False

    # Step 2: Create debug script if it doesn't exist
    script_path = output_file.parent / "check_scanlines.script"
    if not script_path.exists():
        print(f"Creating default script: {script_path}")
        script_path.write_text(DEFAULT_SCRIPT)

    # Step 3: Run headless Stella
    output_text = run_headless_stella(output_file, script_path)
    if output_text is None:
        print("WARNING: Could not validate ROM (no Stella output)")
        return True  # Assembly succeeded even if validation couldn't run

    # Step 4: Parse and report
    passed = parse_and_report(output_text, output_file)

    if passed:
        print("\nBuild and validation PASSED")
    else:
        print("\nBuild succeeded but validation FAILED")

    return passed


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 build_and_run.py <source.asm> [output.a26]")
        sys.exit(1)

    source = sys.argv[1]
    output = sys.argv[2] if len(sys.argv) > 2 else None

    success = build_and_run(source, output)
    sys.exit(0 if success else 1)
